import { StyleSheet ,Dimensions} from "react-native";
const { height }= Dimensions.get('window');
const styles=StyleSheet.create({
    container:{
        color:"#000000",
        fontWeight:"500",
        fontSize:14,
        margin:32
    },
    mainImage:{
        width:"auto",
        height: height/2,
        flexDirection:"column",
        justifyContent:"space-between",
        alignItems:"center",
        
        },
     header:{
            width:"100%",
            flexDirection:"row",
            alignItems:"center",
            justifyContent:"space-between"
        },
        icon:{
            width:28,
            height:28,
            borderRadius:20,
            margin:16
        },
        share:{
            width:36,
            height:36,
            borderRadius:20,   
            margin:16        
        },
        footer:{
         flexDirection:'row',
         alignItems:"center",
         justifyContent:"center",
         borderRadius:15,
         backgroundColor:"rgba(256,256,256,0.35)",
         margin:16,
         paddingHorizontal:8
        },
        smallImage:{
         width:40,
         height:40,
         marginVertical:8,
         marginHorizontal:4,
         borderRadius:10
        },
        moreImage:{
            color:"#fff",
            fontWeight:"bold",
            fontSize:20,
           
        },
        moreImageContainer:{
            position:"absolute",
            top:8,
            left:4,
            backgroundColor:'rgba(0,0,0,0.38)',
            width:40,
            height:40,
            borderRadius:10,
            justifyContent:"center",
            alignItems:"center"
        },
        headerContainer:{
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-between",
        marginVertical:40
        },
        
        city:{
           color:"black",
           fontSize:20,
           fontWeight:"400",
           marginTop:8
        },
        title:{
            color:"black"
        },
        map:{
            width:"auto",
            height:200,
            borderRadius:10,
          },
          mapText:{
            fontWeight:'bold',
            fontSize:18,
            color:"#4681A3",
            textAlign:"center",
            padding:16,
            marginBottom:60
        }
})
export default styles